openapi: 3.0.0
info:
  title: Pages API
  description: This is a simple API for managing pages.
  version: 1.0.0
servers:
  - url: http://example.com/api
    description: Main production server
paths:
  /pages:
    get:
      summary: List all pages
      description: This endpoint returns all pages.
      responses:
        "200":
          description: A JSON array of pages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Page"
components:
  schemas:
    Page:
      type: object
      properties:
        id:
          type: integer
          description: The page ID.
        title:
          type: string
          description: The page title.
        content:
          type: string
          description: The page content.
