openapi: 3.0.0
info:
  title: TradingView API
  description: This API provides trading view data for different countries.
  version: 1.0.0
servers:
  - url: https://stock-inpiniti.vercel.app/api
    description: Main production server
paths:
  /tradingview/{countryCode}:
    get:
      summary: Get trading view data for a specific country
      description: This endpoint returns trading view data for the specified country code.
      parameters:
        - in: path
          name: countryCode
          required: true
          schema:
            type: string
            example: "us" # 예시 값
            enum:
              - "us"
              - "kr"
              - "jp"
              - "cn"
              - "uk"
              - "de"
          description: 거래 데이터를 얻기 위한 국가 코드입니다. 예시로는 'us' (미국), 'kr' (대한민국), 'jp' (일본), 'cn' (중국), 'uk' (영국), 'de' (독일) 등이 있습니다.
      responses:
        "200":
          description: 지정된 국가에 대한 거래 뷰 데이터
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TradingViewItem"
components:
  schemas:
    TradingViewItem:
      type: object
      properties:
        name:
          type: string
          description: 주식의 심볼입니다.
          example: "005930"
        description:
          type: string
          description: 주식의 설명입니다.
          example: "SAMSUNG ELECTRONICS"
        logoid:
          type: string
          description: 주식의 로고 ID입니다.
          example: "samsung"
        update_mode:
          type: string
          description: 업데이트 모드입니다.
          example: "delayed_streaming_1200"
        type:
          type: string
          description: 자산 유형입니다.
          example: "stock"
        close:
          type: integer
          description: 주식의 종가입니다.
          example: 86700
        pricescale:
          type: integer
          description: 가격 스케일입니다.
          example: 1
        minmov:
          type: integer
          description: 최소 움직임입니다.
          example: 100
        fractional:
          type: string
          description: 소수점 여부입니다.
          example: "false"
        minmove2:
          type: integer
          description: 최소 움직임 2입니다.
          example: 0
        currency:
          type: string
          description: 거래 통화입니다.
          example: "KRW"
        change:
          type: number
          description: 변동율입니다.
          example: 2.7251184834123223
        volume:
          type: integer
          description: 거래량입니다.
          example: 25193080
        relative_volume_10d_calc:
          type: number
          description: 10일간의 상대 거래량 계산입니다.
          example: 1.0449843880624579
        market_cap_basic:
          type: number
          description: 기본 시가총액입니다.
          example: 558983075378418
        fundamental_currency_code:
          type: string
          description: 기본 통화 코드입니다.
          example: "KRW"
        price_earnings_ttm:
          type: number
          description: TTM (추적 12개월) 기준의 주가수익비율입니다.
          example: 29.90499730786039
        earnings_per_share_diluted_ttm:
          type: number
          description: TTM 기준의 희석 주당 순이익입니다.
          example: 2899.181
        earnings_per_share_diluted_yoy_growth_ttm:
          type: number
          description: TTM 기준의 희석 주당 순이익 연간 성장률입니다.
          example: -56.239496682084734
        dividends_yield_current:
          type: number
          description: 현재 배당 수익률입니다.
          example: 1.7109
        sector_tr:
          type: string
          description: 부문(한국어)입니다.
          example: "Electronic technology"
        market:
          type: string
          description: 시장입니다.
          example: "korea"
        sector:
          type: string
          description: 부문입니다.
          example: "Electronic Technology"
        recommendation_mark:
          type: number
          description: 추천 마크입니다.
          example: 1.225
        exchange:
          type: string
          description: 거래소입니다.
          example: "KRX"
        perf_w:
          type: number
          description: 주간 성과입니다.
          example: -1.3651877133105803
        perf_1_m:
          type: number
          description: 1개월 성과입니다.
          example: 8.782936010037641
        perf_3_m:
          type: number
          description: 3개월 성과입니다.
          example: 6.773399014778325
        perf_6_m:
          type: number
          description: 6개월 성과입니다.
          example: 18.6046511627907
        perf_y_t_d:
          type: number
          description: 연초 대비 성과입니다.
          example: 10.869565217391305
        perf_y:
          type: number
          description: 연간 성과입니다.
          example: 19.586206896551722
        perf_5_y:
          type: number
          description: 5년간 성과입니다.
          example: 86.65231431646932
        perf_10_y:
          type: number
          description: 10년간 성과입니다.
          example: 221.349147516679
        perf_all:
          type: number
          description: 전체 성과입니다.
          example: 27291.36315251274
        volatility_w:
          type: number
          description: 주간 변동성입니다.
          example: 2.226905622559229
        volatility_m:
          type: number
          description: 월간 변동성입니다.
          example: 1.8625828300600529
        premarket_close:
          type: number
          description: 프리마켓 종가입니다.
          example: null
        premarket_change:
          type: number
          description: 프리마켓 변동입니다.
          example: null
        premarket_gap:
          type: number
          description: 프리마켓 갭입니다.
          example: null
        premarket_volume:
          type: number
          description: 프리마켓 거래량입니다.
          example: null
        gap:
          type: number
          description: 갭입니다.
          example: 0.35545023696682465
        volume_change:
          type: number
          description: 거래량 변화입니다.
          example: -4.370213828479434
        postmarket_close:
          type: number
          description: 포스트마켓 종가입니다.
          example: null
        postmarket_change:
          type: number
          description: 포스트마켓 변동입니다.
          example: null
        postmarket_volume:
          type: number
          description: 포스트마켓 거래량입니다.
          example: null
        perf_1_y_market_cap:
          type: number
          description: 시가총액 대비 1년 성과입니다.
          example: 21.587838969640796
        price_earnings_growth_ttm:
          type: number
          description: PEG (주가수익성장비율)입니다.
          example: null
        price_sales_current:
          type: number
          description: 현재 PSR (주가매출비율)입니다.
          example: 2.1463461711513148
        price_book_fq:
          type: number
          description: FQ (최근분기) PBR (주가순자산비율)입니다.
          example: 1.625448330427328
        price_to_cash_f_operating_activities_ttm:
          type: number
          description: TTM 기준의 영업활동 현금 흐름 대비 주가입니다.
          example: 11.84673669770286
        price_free_cash_flow_ttm:
          type: number
          description: TTM 기준의 자유 현금 흐름 대비 주가입니다.
          example: null
        price_to_cash_ratio:
          type: number
          description: 현금비율입니다.
          example: 6.046898043599228
        enterprise_value_current:
          type: number
          description: 현재 기업 가치입니다.
          example: 486695457378418
        enterprise_value_to_revenue_ttm:
          type: number
          description: TTM 기준의 매출 대비 기업 가치입니다.
          example: 1.8221079282389996
        enterprise_value_to_ebit_ttm:
          type: number
          description: TTM 기준의 EBIT 대비 기업 가치입니다.
          example: 38.86370453682033
        enterprise_value_ebitda_ttm:
          type: number
          description: TTM 기준의 EBITDA 대비 기업 가치입니다.
          example: 9.440499554281246
        dps_common_stock_prim_issue_fy:
          type: number
          description: 연간 배당금입니다.
          example: 1444
        dps_common_stock_prim_issue_fq:
          type: number
          description: 분기 배당금입니다.
          example: 361
        dividends_yield:
          type: number
          description: 배당 수익률입니다.
          example: 1.7109004
        dividend_payout_ratio_ttm:
          type: number
          description: TTM 기준의 배당 성향입니다.
          example: 49.80716967998893
        dps_common_stock_prim_issue_yoy_growth_fy:
          type: number
          description: 연간 배당 성장률입니다.
          example: 0
        continuous_dividend_payout:
          type: number
          description: 연속 배당 지급입니다.
          example: 8
        continuous_dividend_growth:
          type: number
          description: 연속 배당 성장입니다.
          example: 0
        gross_margin_ttm:
          type: number
          description: TTM 기준의 매출 총이익률입니다.
          example: 31.6295449362965
        operating_margin_ttm:
          type: number
          description: TTM 기준의 영업 이익률입니다.
          example: 4.68845662027071
        pre_tax_margin_ttm:
          type: number
          description: TTM 기준의 세전 이익률입니다.
          example: 5.98941339048204
        net_margin_ttm:
          type: number
          description: TTM 기준의 순이익률입니다.
          example: 7.3728030628052
        free_cash_flow_margin_ttm:
          type: number
          description: TTM 기준의 자유 현금 흐름 마진입니다.
          example: -3.024034782571713
        return_on_assets_fq:
          type: number
          description: FQ 기준의 총자산 이익률입니다.
          example: 4.25802336674004
        return_on_equity_fq:
          type: number
          description: FQ 기준의 자기자본 이익률입니다.
          example: 5.5291903621015
        return_on_invested_capital_fq:
          type: number
          description: FQ 기준의 투자 자본 수익률입니다.
          example: 5.46229392982746
        research_and_dev_ratio_ttm:
          type: number
          description: TTM 기준의 연구 개발 비율입니다.
          example: 11.07827288643204
        sell_gen_admin_exp_other_ratio_ttm:
          type: number
          description: TTM 기준의 판매, 총무 및 관리비 비율입니다.
          example: 15.862815429593713
        total_assets_fq:
          type: number
          description: FQ 기준의 총자산입니다.
          example: 470899812000000
        total_current_assets_fq:
          type: number
          description: FQ 기준의 유동자산입니다.
          example: 208544280000000
        cash_n_short_term_invest_fq:
          type: number
          description: FQ 기준의 현금 및 단기투자입니다.
          example: 97392826000000
        total_liabilities_fq:
          type: number
          description: FQ 기준의 총부채입니다.
          example: 98983688000000
        total_debt_fq:
          type: number
          description: FQ 기준의 총채무입니다.
          example: 15504153000000
        net_debt_fq:
          type: number
          description: FQ 기준의 순채무입니다.
          example: -81888673000000
        total_equity_fq:
          type: number
          description: FQ 기준의 총자본입니다.
          example: 371916124000000
        current_ratio_fq:
          type: number
          description: FQ 기준의 유동비율입니다.
          example: 2.55036534939832
        quick_ratio_fq:
          type: number
          description: FQ 기준의 당좌비율입니다.
          example: 1.89795653938399
        debt_to_equity_fq:
          type: number
          description: FQ 기준의 부채비율입니다.
          example: 0.04279190772493101
        cash_n_short_term_invest_to_total_debt_fq:
          type: number
          description: FQ 기준의 현금 및 단기투자의 총부채 비율입니다.
          example: 6.281725031996266
        cash_f_operating_activities_ttm:
          type: number
          description: TTM 기준의 영업활동 현금흐름입니다.
          example: 49711959000000
        cash_f_investing_activities_ttm:
          type: number
          description: TTM 기준의 투자활동 현금흐름입니다.
          example: -55427376000000
        cash_f_financing_activities_ttm:
          type: number
          description: TTM 기준의 재무활동 현금흐름입니다.
          example: -6343413000000
        free_cash_flow_ttm:
          type: number
          description: TTM 기준의 자유 현금흐름입니다.
          example: -8077370000000
        capital_expenditures_ttm:
          type: number
          description: TTM 기준의 자본지출입니다.
          example: -60785535000000
        recommend_all:
          type: number
          description: 전체 추천입니다.
          example: 0.5575757575757576
        recommend_m_a:
          type: number
          description: 통합 및 인수 추천입니다.
          example: 0.9333333333333333
        recommend_other:
          type: number
          description: 기타 추천입니다.
          example: 0.18181818181818182
        r_s_i:
          type: number
          description: RSI (상대강도지수)입니다.
          example: 63.95523439654242
        mom:
          type: number
          description: 모멘텀입니다.
          example: 4900
        a_o:
          type: number
          description: AO (멜린저 오실레이터)입니다.
          example: 6238.823529411762
        c_c_i20:
          type: number
          description: CCI (상품채널지수) 20입니다.
          example: 71.7592592592593
        stoch_k:
          type: number
          description: 스토캐스틱 K입니다.
          example: 71.35435544279328
        stoch_d:
          type: number
          description: 스토캐스틱 D입니다.
          example: 79.16053178829547
