// 선택된 국가
export const nameList: any = {
  Israel: "il", // 이스라엘
  Brazil: "br", // 브라질
  France: "fr", // 프랑스
  Hong: "hk", // 홍콩
  Belgium: "be", // 벨기에
  Finland: "fi", // 핀란드
  Italy: "it", // 이탈리아
  Sweden: "se", // 스웨덴
  Singapore: "sg", // 싱가포르
  Netherlands: "nl", // 네덜란드
  Switzerland: "ch", // 스위스
  Chile: "cl", // 칠레
  Canada: "ca", // 캐나다
  Germany: "de", // 독일
  Ireland: "ie", // 아일랜드
  Norway: "no", // 노르웨이
  Denmark: "dk", // 덴마크
  Portugal: "pt", // 포르투갈
  Spain: "es", // 스페인
  United: "uk", // 영국, 아랍에미라이트도 섞여 있음 ㅠㅠ
  Colombia: "co", // 콜롬비아
  Czech: "cz", // 체코
  Greece: "gr", // 그리스
  Egypt: "eg", // 이집트
  Hungary: "hu", // 헝가리
  India: "in", // 인도
  Indonesia: "id", // 인도네시아
  Korea: "kr", // 한국
  Malaysia: "my", // 말레이시아
  Mexico: "mx", // 멕시코
  Peru: "pe", // 페루
  Philippines: "ph", // 필리핀
  Poland: "pl", // 폴란드
  Thailand: "th", // 태국
  Turkey: "tr", // 터키
  Argentina: "ar", // 아르헨티나
  Jordan: "jo", // 요르단
  Morocco: "ma", // 모로코
  Oman: "om", // 오만
  Pakistan: "pk", // 파키스탄
  Qatar: "qa", // 카타르
  Sri: "lk", // 스리랑카
  Australia: "au", // 호주
  China: "cn", // 중국
  Japan: "jp", // 일본
  US: "us", // 미국
  Austria: "at", // 오스트리아
  Cyprus: "cy", // 키프로스
  Taiwan: "tw", // 대만
};
