name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test
